### ISSUE TITLE
Anki Cloze Macros no longer being rendered

### ISSUE THREAD

**Issue by Insufficient** [debanjandhar12/logseq-anki-sync#159]
**Describe the bug**
This worked in 0.8.16 but since upgrading to 0.8.17, it no longer works.
![image](https://user-images.githubusercontent.com/4232717/218205418-3240f3f1-4201-45a0-b657-70e4e6f53edc.png)

**Steps to Reproduce:**
1. Upgrade to Logseq version 0.8.17
2. Create a new block with contents `I am a {{c1 Pikachu}}`

**Expected behavior**
The Anki Cloze macro syntax should be rendered like below:
![image](https://user-images.githubusercontent.com/4232717/218205706-6e73272e-89e1-4548-b50e-4914b45633cb.png)

**Developer console screenshot:**
![image](https://user-images.githubusercontent.com/4232717/218205190-0aaf5015-0734-4dbe-ba79-93bd041566db.png)

**Device Information (please complete the following information):**
 - OS with version: Windows 11 Home 21H2
 - Logseq Anki Sync Plugin Version: 4.3.1
 - Anki Version: N/A
 - AnkiConnect Addon Version: N/A
 - Logseq Version: 0.8.17

**Comment by Tubo** [comment]
I have a similar issue but the rendering turns the `{{c1 blah blah}}` synx into a line break. Like this:

![Screenshot_20230216_104356](https://user-images.githubusercontent.com/7521921/219175899-ac80305a-1ced-427b-8c3b-b7fe15f94c98.png) (Note there's a weird line break in the sentence and the cloze itself was not rendered).

The original text was this:
![Screenshot_20230216_104339](https://user-images.githubusercontent.com/7521921/219176054-4b564822-7510-4fb7-a824-5a54a64b4c2a.png).

This only started since 0.8.17.

**Comment by Tubo** [comment]
I've tried disabling the "Render Anki Cloze Macros in Logseq" option, and didn't help. It shows this instead:

![Screenshot_20230216_105206](https://user-images.githubusercontent.com/7521921/219177632-8cdbb9fa-db7d-4551-88bc-0743036d1347.png).

Looks like Logseq have taken over the rendering of double braces.

**Comment by Dunrar** [comment]
This is a problem of LogSeq itself, introduced here: https://github.com/logseq/logseq/pull/8299. For now, you can mostly get around this by putting this into the `custom.css` file:
``` css
.macro {display: inline;}
.hiccup_html {display: inline;}
```
and this into the `config.edn`:
``` edn
 :macros {
        "c1" "[:span {:style \"background-color:rgb(59 130 246 / 0.1);white-space: initial;\"} \"$1\"]"
        "c2" "[:span {:style \"background-color:rgb(59 130 246 / 0.1);white-space: initial;\"} \"$1\"]"
        "c3" "[:span {:style \"background-color:rgb(59 130 246 / 0.1);white-space: initial;\"} \"$1\"]"
 }
```

You can of course add as many c's as you actually use. The line break will hopefully be fixed by the LogSeq team soon, it happens for all self-defined macros. That you can see the double curly braces and the c* now will probably have to be changed in the plugin.

**Comment by debanjandhar12** [comment]
> I have a similar issue but the rendering turns the `{{c1 blah blah}}` synx into a line break. Like this:
> 
> ![Screenshot_20230216_104356](https://user-images.githubusercontent.com/7521921/219175899-ac80305a-1ced-427b-8c3b-b7fe15f94c98.png) (Note there's a weird line break in the sentence and the cloze itself was not rendered).
> 
> The original text was this: ![Screenshot_20230216_104339](https://user-images.githubusercontent.com/7521921/219176054-4b564822-7510-4fb7-a824-5a54a64b4c2a.png).
> 
> This only started since 0.8.17.

It is a different bug than OP. That bug has been fixed in recent plugin version.

------------
As for the main bug, I am unable to reproduce it.
@Insufficient can you attach image of the block in anki? Also, can you paste the contents of those blocks?

**Comment by Insufficient** [comment]
Sorry for the late response, I have updated to `0.9.4` now and I cannot reproduce the issue. Thanks.
