### ISSUE TITLE
Can't create (or point to) a deck

### ISSUE THREAD

**Issue by saligari** [debanjandhar12/logseq-anki-sync#19]
Hello,
In the Documentation you say you set or change a deck by 

> deck:: [[Example_Deck]] 

However this does nothing for me. All cards end up in the logseq created "Default" deck

**Comment by debanjandhar12** [comment]
> Hello, In the Documentation you say you set or change a deck by
> 
> > deck:: [[Example_Deck]]
> 
> However this does nothing for me. All cards end up in the logseq created "Default" deck

Can you provide me some screenshot? Also, please mention Logseq Version, AnkiConnect Version, Anki Version, Logseq Anki Sync Version.

Also, please ensure that.
- The property is declared in the same block as the card or in page property.
- Are you using org mode? If yes, then please use org mode's logseq property syntax instead of the above.

**Comment by saligari** [comment]
I am on 
Logseq 0.5.9, 
Anki ⁨2.1.49, 
AnkiConnect (latest updated)
Logseq Anki Sync 1.0

Your comment was illuminating, I am using org mode and apparently I can't use 

#+PROPERTY: deck name_of_deck

to create/assign a deck because perhaps logseq has not implemented this (or I am using it wrong) and I have to use
:PROPERTY:
:deck: name_of_deck
:END:

Sorry for bothering, I'm new both with Logseq and org mode and am mostly reading up the docs when I need to.
