### ISSUE TITLE
Disable cards on a page

### ISSUE THREAD

**Issue by thomask-gh** [debanjandhar12/logseq-anki-sync#247]
Hi and firstly thanks a lot for the amazing work that you do with this plugin, it’s helped me a lot!

**Describe the solution you'd like**
I have a page in logseq in which I have a bunch of cards that I don’t really care about anymore, but I still want to keep the page in logseq, and I don’t want to have to go through the hassle of removing every single `#card` or `:->` from this page. I would like to be able to specify something like `deck:: none` or `deck: null` or `cards:: disabled` in the page or block properties, that cause all the children cards to stop being synced to anki.

**Describe how it will help your workflow**
It would mean that I can delete the cards from anki, keep them in logseq and they won’t be brought back to anki every time I sync.

**Describe alternatives you've considered**
Manually deleting every single `#card` or `:->` from the page. But 1) it’s annoying 2) I might need to bring them back in the future, so it will be even more annoying to re-add the cards markers…

**Comment by jaker-dotcom** [comment]
I think this has been solved by now? At least there is a property "disable-anki-sync:: true" which works on blocks but I never tested on pages.
Workaround: If it's the entire page you could just search and replace within the file. To open in external program hit ctrl+d -> ctrl-a or ctrl+d -> ctrl+i to open file browser. 

E.g. using vim it's a matter of seconds to replace all occurences of "#card" with "~~#card~~" and "->" with "-.>". I like to keep placeholders so that I can reactivate them easily.

**Comment by thomask-gh** [comment]
I have tried `disable-anki-sync:: true` on a page and it indeed works, so this issue is solved, thanks a lot!

**Comment by jaker-dotcom** [comment]
Happy to help :)
