### ISSUE TITLE
Support for Anki extensions such as hierarchical tags, image occlusion, and cloze overlapper?

### ISSUE THREAD

**Issue by debanjandhar12** [debanjandhar12/logseq-anki-sync#31]
### Discussed in https://github.com/debanjandhar12/logseq-anki-sync/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **Malam9** January 25, 2022</sup>
Will/does the extension support making card with popular extensions such as those mentioned above?</div>

**Comment by debanjandhar12** [comment]
I will look into hierarchical tags.

As for image occlusion and cloze overlapper, I dont think it would be possible but you can use them parallelly with the plugin in the deck. The structure of the plugin doesn't support external anki plugins to interfere with rendering.

This doesn't however mean that having features of image occlusion and close overlapped in Logseq are impossible, but just that the features need to be added one at a time without actual dependency on those plugins.

**Comment by thiswillbeyourgithub** [comment]
Just chiming in to say that image occlusion and close overlapper might be harder to support than closet (which apparently allows to do both of them) : https://ankiweb.net/shared/info/272311064

**Comment by thiswillbeyourgithub** [comment]
Chiming in again to say that the upcoming [whiteboard feature](https://discord.com/channels/725182569297215569/735735090784632913/977046903906787380) might provide helpful code to create image occlusion cards.

**Comment by skydtrtzmr** [comment]
Hi! 

It seems that now we can only use `::` as separater in order to show hierarchical(nested) tags correctly in Anki. But it is `/` instead of `::` that work as hierarchy(namespace) separater in Logseq. 
So can you consider implementing a way to transform `Tags:: parentTag/childTag` in Logseq to `parentTag::childTag` in Anki? That means when we specify the hierarchical tag once, it works as hierarchical tag both in Logseq and Anki.

(I saw #35 and this issue so I dont know if I should write a new one, and wonder if you're still working on this feature)

Thanks a lot!  :)

**Comment by debanjandhar12** [comment]
Closing as V4 supports most of it.

**Comment by jaker-dotcom** [comment]
Just that I don't miss a thing: Overlapped clozes are still not possible, not via {{c1 lkajdsf}} nor per replacecloze:: syntax, right?
At least I don't get it to work.
