### ISSUE TITLE
Could we have the option to only sync the current page or selected page avoiding the performance problem when large amount of card?

### ISSUE THREAD

**Issue by WaytrueDeng** [debanjandhar12/logseq-anki-sync#68]
**Describe the solution you'd like**
as above
**Describe how it will help your workflow**

**Describe alternatives you've considered**

**Comment by WaytrueDeng** [comment]
![image](https://user-images.githubusercontent.com/61548208/168200509-8f273386-886d-4434-837b-43f679e3c223.png)

**Comment by Conchilardo** [comment]
Yes please this would be awesome

**Comment by debanjandhar12** [comment]
I need clear idea about the need for this before I can decide.

Specifically, is the speed of sync slow? How long does it take? How many cards do you have? What type of cards do you mostly use?

**Comment by Conchilardo** [comment]
I have 500+ normal cards (text front side and text backside) which takes about 5 minutes to sync. It'd be awesome to be able to sync a single page at a time, or single cards

**Comment by debanjandhar12** [comment]
> I have 500+ normal cards (text front side and text backside) which takes about 5 minutes to sync. It'd be awesome to be able to sync a single page at a time, or single cards
What type of cards are majority of them?
Multiline cards? Clozes? Replaceclozes?

**Comment by alan-nicolas** [comment]
It is quite slow. Some sort of fix would be appreciated, even what the OP proposes.

**Comment by alan-nicolas** [comment]
@debanjandhar12 Hi. Thanks for all of your work, man.

1. Skip ... Dependency Hash option checked. I also tried checking activeCacheForLogseqAPIv0 to no avail.
2. Linux (Manjaro  + KDE)
3. Around +40 seconds
4. 2600+ cards

It is frustrating enough for me to switch away into making everything inside of Anki again. The time it takes is not ideal for adding a few cards at a time, stopping to make reviews, and repeating.

(Hope you fid a solution. Is it because you can't cache the files unlike with Obsidian?)

**Comment by ludivn** [comment]
Hi,

I would be very interested in a curent page only syncing.
In my case it's not a problem of syncing time or error (well not yet). For organization reasons, I want to remove some of my notes from my Logseq file while keeping coresponding cards in Anki. But with Anki pluggin automaticallly syncing all, those cards are deleted from anki. 

Maybe someone have a solution not involving massive coding ?

And a big thx to the dev, who do an amazing work!

**Comment by debanjandhar12** [comment]
> (Hope you fid a solution. Is it because you can't cache the files unlike with Obsidian?)

Mainly because:
* The plugin supports block & page references and embedded. This means the plugin needs to calculate the hashes of those as well.
* Datascript is very slow. (even simple operation of block retrival with uuid through logseq api takes a long time)
* I dont have any experience with datascript. This means most of the datascript queries are unoptimized.

**Comment by hedyhli** [comment]
I'd like to bump this. For me I only wish to sync cards from specific pages to Anki so would love for this feature to be implemented!

**Comment by debanjandhar12** [comment]
I am considering revisiting this issue once more. Based on my understanding, the motive behind this feature request has is no longer performance but rather unique workflow requirements?

**Comment by jenny923432** [comment]
For me the motivation is performance. I have 538 cards, mostly swift arrows and single-line #cards, and the plugin consistently saturates a CPU core for over 6 hours to sync them.

**Comment by debanjandhar12** [comment]
If syncing is taking too long, please ensure that the following settings are enabled:
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/49021233/c46a3b1c-8b89-4c88-9104-18d52a042c23)

**Comment by debanjandhar12** [comment]
Coming later this week:
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/49021233/b6190b99-f1d0-4213-b99f-407d074bf91d)
