### ISSUE TITLE
[Feedback Wanted] Swift cards?

### ISSUE THREAD

**Issue by debanjandhar12** [debanjandhar12/logseq-anki-sync#72]
The next version (v3.2.0) of the plugin will introduce Swift cards. It is an easier way to make cards. 
![demo](https://user-images.githubusercontent.com/49021233/171670018-929ea489-185a-41f2-afc6-001f08d8f958.gif)

More info: https://github.com/debanjandhar12/logseq-anki-sync/wiki/Making-Swift-cards
Before releasing it I wanted to feedback and suggestions for the feature. Please comment bellow if you have any. Also, if you have a better name, please suggest!

**Comment by joao-gabrielC** [comment]
I would definately use that. Some suggestions that i'd also like is a way to put hints for the clozes, maybe using block properties, and a way to end the cloze before the end of the block, leaving the rest visible in the notes. Would be something like (if :-< is the text to end the cloze):

``` Symptoms :-> pain in the chest, chronic cough, fatigue, fever >-: or only some of those ```
``` Symptoms [...] or only some of those ```

Anyway, love the way this plugin is going

**Comment by thiswillbeyourgithub** [comment]
Sooo promising! Great idea!


I think it might be useful to add the following behavior :
tuberculosis:
* description :-> this is the description answer thingy placeholder
    *  adding a new bullet point here will automatically be added to an additionnal field like "More"
        
I hope my example was clear. The idea is to make it easy to add additional content to another field than "Body".

Also, not really a fan of the name "swift cards", what do you think of "quick cards" or "short cards" ? Swift is actually the name of a company that deals with credit cards so you might even get sued lol.


I concur : ` love the way this plugin is going` !

**Comment by Tubo** [comment]
Love the idea. This is big! This could speed up card creation by a magnitude.

- The choice of `:->` is slightly noisy on the eyes. I wonder if `::` (from org-mode item list) would be better? If you do go with `:->` can we at least transform it to something simple in Anki?
- The support for "extra" field and "cloze hints" is also very important because the stem/heading is set in the parent. I feel like hints could be a property.
- In terms of naming it, I feel like this is cloze generation from an item list, so a name such as "item list cloze" would be more informative than swift cards.

**Comment by thiswillbeyourgithub** [comment]
Another thing comes to mind. In your example : 
* tuberculosis
    * description :-> some description

Can you (@debanjandhar12) show the content of the card in anki? I want to make sure that the "tuberculosis" is in a field of its own, this allows to search for it in anki by filtering by fields.

But you can't to bidirectionnal cloze over multiple fields so I think it might be important to have one field for "tuberculosis" that is not shown in the content, just so that you can search for it.

I'm pretty sure I'm not very clear :) would you mind sharing a picture of the fields in anki for those example cards?

**Comment by debanjandhar12** [comment]
- > The choice of :-> is slightly noisy on the eyes. I wonder if :: (from org-mode item list) would be better? If you do go with :-> can we at least transform it to something simple in Anki?

   I agree that ":-> is slightly noisy on the eyes". However as `::` is used in logseq for properties, and hence would cause problems.

  > 3\. Maybe ":>" ":<" and ":<>" would be easier to type than the current prefix

     Sounds like a good idea. Any other feedback on this is welcome too. 


- > Some suggestions that i'd also like is a way to put hints for the clozes, maybe using block properties, and a way to end the cloze before the end of the block, leaving the rest visible in the notes.
 
    > The support for "extra" field and "cloze hints" is also very important because the stem/heading is set in the parent. I feel like hints could be a property.
   
    The "extra" field will be supported via org mode syntax and extra properties just like cloze and multiline cards. Can someone create a "cloze hints" feat req? I believe types of other cards can also benefit from it.
   
- > In terms of naming it, I feel like this is cloze generation from an item list, so a name such as "item list cloze" would be more informative than swift cards.
 
   Thanks for the feedback! I am not sure however since the syntax is for not just for lists but also for creating cards faster too. I will however definitely consider it.

**Comment by profsilva** [comment]
Maybe:
Card Forward           >> 
Card Reversed         <<
Card Bidirectional     <>
Card Multiline            ;;  (double semicolon)

with the exception of the bidirectional card, the use of the same key tends to be faster, if you want fastest, just eliminate the use of shift. This is intuitive way. I use it like this in obsidian through the obsidian_to_anki plugin.

**Comment by thiswillbeyourgithub** [comment]
I would rather have ">>>" for multiline, no ? It would be more coherent with the rest, especially because ";;" is used to add comment in Datalog.

I don't know if having a command start with "<" is an issue for the "formatting" command in Logseq. Is it?

Anyway it would be awesome to have keybiding for this. Like `t` for theme (tt, ti) maybe you could use `c` (cc for >>, cr for <<, cb for <>, cm for multiline)?

**Comment by profsilva** [comment]
> Anyway it would be awesome to have keybiding for this. Like t for theme (tt, ti) maybe you could use c (cc for >>, cr for <<, cb for <>, cm for multiline)?

Yes, I liked it that way, much faster, you don't even have to hold shift! Great idea!

**Comment by debanjandhar12** [comment]
Following up on this:
- It is not a very good idea to use `>>` as `>>` is very often repeated inside code blocks. Yes, the data inside code blocks can be ignored, but during initial fetch, it is not possible to do something like match `>>` everywhere except codeblocks. It is only possible to do that after initial fetch, however by then lots of blocks will already be fetched (costly operation).
- I will most likely go for `:>` `:<` `:<>` but suggestions are still welcome

**Comment by KyleUltimate** [comment]
I don't know if this is the correct place to ask, but, are swift cards implemented in 3.0.0? Because I can't seem to make it work

**Comment by debanjandhar12** [comment]
> I don't know if this is the correct place to ask, but, are swift cards implemented in 3.0.0? Because I can't seem to make it work ![image](https://user-images.githubusercontent.com/68589851/179159531-acd2abc5-a0d8-49b5-82ef-113867ebf95f.png) ![image](https://user-images.githubusercontent.com/68589851/179159561-30d7944d-6001-4e8a-af3d-9e496e41b620.png)

It is not implemented yet. It will be added in 3.2.0 most likely.

**Comment by debanjandhar12** [comment]
Implemented in v3.2.0:
- Decided on `:->`, `:<-` , `:<->` as there was slight performance problem with `:>` etc
- I will however provide an option to customize in future updates.
