### ISSUE TITLE
logseq becomes very slow after performing synchronization

### ISSUE THREAD

**Issue by largomst** [debanjandhar12/logseq-anki-sync#9]
Before I perform the sync to Anki function, everything is fine in logseq. After performing the sync to Anki, editing blocks in logseq, such as creating and deleting blocks, becomes very slow.

This phenomenon is reproducible every time I restart logseq.

My logseq contain about three hundred cards. 
platform: Logseq macOS Desktop 0.5.4

**Comment by debanjandhar12** [comment]
> My logseq contain about three hundred cards.
Wow that's double of my own. Maybe there is a memory leak? I will look into it.

In the meanwhile, can you give me some more details? Specifically:
- Anki and AnkiConnect Version:
- Logseq Version:
- Logseq Anki Sync plugin Version:

**Comment by largomst** [comment]
Anki:  ⁨2.1.49
AnkiConnect: 2021-07-14 updated
Logseq Version: 0.5.4/macOS Desktop
Logseq Anki Sync plugin Version: 0.3.0
I just use the #card tag and clozes.
I don't know how to get the number of blocks, I just know there are 1032 pages.

**Comment by KimhengMok** [comment]
I would like to share mine as well since i wonder how long it would be if there're more cards from those hundreds or thousand pages.

Anki: 2.1.49
AnkiConnect: Latest Update on 2021-12-27
Logseq Version: Version 0.5.9 (0.5.9)
Logseq Anki Sync plugin Version: Version 1.0.0 (latest)
I mainly use multiline cards with #card tag. 
I just have 46 pages and around 300 cards.
For the sync process, it takes about 50 seconds.

**Comment by debanjandhar12** [comment]
I believe Memory leak should be fixed. Also, Syncing speed has been improved in V2.0.0.
